solarwinds/solarwinds-otel-collector-releases

- README.md
- build/docker/README.md
Adjusted documentation to make it more user friendly
**Tracking Issue:** https://swicloud.atlassian.net/browse/NH-97805
User review.
> [documentation] Adjusted documentation to make it more user friendly

- CHANGELOG.md
Adds changelog entry for v0.113.3
N/A, docs only change.
> [docs] Add changelog for v0.113.3

- build/docker/Dockerfile
- extension/solarwindsextension/README.md
- extension/solarwindsextension/config_test.go
- extension/solarwindsextension/internal/config.go
- extension/solarwindsextension/internal/heartbeat.go
- extension/solarwindsextension/testdata/full.yaml
- internal/e2e/signals_processing_test.go
- internal/e2e/testdata/emitting_collector.yaml
solarwindsextension now has optional attributes
If any are specified, the uptime metric will be enriched with the given attributes, and their values. 
Tested on the docker image.
> feature: optional custom attributes for extension

- CHANGELOG.md
Adds changelog entry for v0.113.4
Testing
N/A, docs only change.
> docs: add remark on v0.113.4 main change

- .github/workflows/buildAndDeploy.yml
- CHANGELOG.md
- README.md
tagging releases with 'latest' tag
None, we will see once new version is released
> build: tagging releases with 'latest' tag

- internal/e2e/config_test.go
- internal/e2e/testdata/invalid_setup.yaml
Introducing additional e2e tests scenarios related to configuration:
- When configuration file is missing.
- When configuration file contains invalid configuration.
Since this change represents additional testing, it is being understood as tested, when newly introduced tests are ran and passed.
> test: introducing configuration related e2e tests

- extension/solarwindsextension/README.md
- extension/solarwindsextension/config_test.go
- extension/solarwindsextension/internal/config.go
- extension/solarwindsextension/internal/heartbeat.go
- extension/solarwindsextension/testdata/full.yaml
- extension/solarwindsextension/testdata/without_entity.yaml
- internal/e2e/containers.go
- internal/e2e/signals_processing_test.go
- internal/e2e/testdata/emitting_collector_without_entity.yaml
- internal/e2e/without_entity_test.go
Adding attribute without_entity to opt out of collector entity creation in solarwinds observability.
Tested on branchbuild of entity service, both cases.
> feature: adding attribute without_entity

- .github/workflows/buildAndDeploy.yml
Due to security we rotate security tokens
> build: Update security token

- .github/workflows/buildAndDeploy.yml
fixing Windows build
https://swicloud.atlassian.net/browse/NH-99740
[Manually running Windows build](https://github.com/solarwinds/solarwinds-otel-collector/actions/runs/13181304903)
> fix: fixing Windows build

- .github/workflows/buildAndTest.yml
Run the basic part of the "Build and Test Images" pipeline on merge to main
> chore: Run the "Build and Test Images" pipeline on merge to main

- .github/workflows/buildAndTest.yml
- .github/workflows/deploy.yml
> chore: Fix pipeline for Windows

- .github/workflows/buildAndTest.yml
- .github/workflows/deploy.yml
* Fix publishing of k8s images
* Add checks for already existing GH release and Docker images
* Fix image tags
* Avoid storing windows build artifacts when not necessary
> chore: Additional pipeline improvements

- .github/workflows/buildAndTest.yml
- pkg/version/go.mod
Rename module 'pkg/version' to 'github.com/solarwinds/solarwinds-otel-collector/pkg/version'
Also fix building of Windows images
> chore: Fixing module name and build pipeline

- .github/workflows/deploy.yml
Uses correct vars for docker login for docker windows deployment.
> chore: use correct docker login (windows deployment)

- .github/workflows/deploy.yml
Create Git tags for Go packages in this repository. E.g. `receiver/swohostmetricsreceiver/v0.119.0`. That way they can be referenced from other repositories.
> chore: Tag Go packages

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/ISSUE_TEMPLATE/technical_improvement.yaml
- .github/workflows/checkPullRequestSemantics.yml
Add additional checks for PR titles:
* Require valid Issue number in PR title for `feature` and `fix` PR types
* Validate Issue number in PR title (if used)
Extend Issue templates with recently added `swohostmetricsreceiver`.
**Tracking Issue:** https://github.com/solarwinds/solarwinds-otel-collector/issues/54
> chore: #54 Add additional checks for PR titles and other Issues improvements

- .github/workflows/deploy.yml
Add missing credentials to use Docker scout. Existing login was improved to use login-action.
**Tracking Issue:** https://github.com/solarwinds/solarwinds-otel-collector/issues/56
No tests added -> github configuration.
> chore: #56 Fix GHA docker credentials

- .github/workflows/deploy.yml
Sarif file has incorrect name set.
**Tracking Issue:** https://github.com/solarwinds/solarwinds-otel-collector/issues/56
No test cases.
> chore: #56 Update path to sarif output artifact

- CHANGELOG.md
- cmd/solarwinds-otel-collector/go.mod
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- pkg/version/version.go
- receiver/swohostmetricsreceiver/go.mod
- receiver/swok8sobjectsreceiver/go.mod
Release 0.119.3 with new `swok8sobjectsreceiver`
**Tracking Issue:** https://github.com/solarwinds/solarwinds-otel-collector/issues/72
No tests
> feature: #72 prepare release 0.119.3

- CHANGELOG.md
- cmd/solarwinds-otel-collector/go.mod
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- pkg/version/version.go
- receiver/swohostmetricsreceiver/go.mod
- receiver/swok8sobjectsreceiver/go.mod
> chore: release 0.119.8

- .github/actions/dockerScoutScan/action.yml
- .github/workflows/buildAndTest.yml
chore: simplified version retrieval in dockerScoutScan.
Copied from here
https://github.com/solarwinds/solarwinds-otel-collector-releases/blob/c410a544185689c8b02194887ed16e51ca2f5bc7/.github/workflows/deploy.yml#L27
> chore: simplified version retrieval in dockerScoutScan

- CHANGELOG.md
- cmd/solarwinds-otel-collector/go.mod
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- pkg/version/version.go
- receiver/swohostmetricsreceiver/go.mod
- receiver/swok8sobjectsreceiver/go.mod
After multiple security fixes we are releasing.
By CI/DC pipeline.
> chore: preparing release v0.123.1

- .github/workflows/buildAndTest.yml
- cmd/connection-check/go.mod
- cmd/connection-check/go.sum
- cmd/connection-check/main.go
Fixing issue with [windows build](https://github.com/solarwinds/solarwinds-otel-collector-releases/actions/runs/14861908427/job/41728760965).
And issue that will come up when releasing.
> chore: fix build issues

- .github/workflows/buildAndTest.yml
- .github/workflows/deploy.yml
- README.md
- build/docker/README.md
feature: #150 align latest tags
Tested
> feature: #150 align latest tags

- CHANGELOG.md
- cmd/solarwinds-otel-collector/go.mod
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- pkg/version/version.go
- processor/swok8sworkloadtypeprocessor/go.mod
- receiver/swohostmetricsreceiver/go.mod
- receiver/swok8sobjectsreceiver/go.mod
> chore: release v0.123.3

- .github/workflows/deploy.yml
- CHANGELOG.md
- cmd/solarwinds-otel-collector/go.mod
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- pkg/version/version.go
- processor/swok8sworkloadtypeprocessor/go.mod
- receiver/swohostmetricsreceiver/go.mod
- receiver/swok8sobjectsreceiver/go.mod
chore: release v0.123.4
Addressing issues with windows image publishing.
> chore: bugfix release 0.123.4

- .github/actions/dockerScoutScan/action.yml
chore: use bigger page_size to fix random issue
> chore: use bigger page_size to fix random issue

- cmd/solarwinds-otel-collector/components_k8s.go
Adding `solarwindsentityconnector` to K8s distribution. 
**Tracking Issue:** https://github.com/solarwinds/solarwinds-otel-collector-releases/issues/164
Verified locally against SWO K8s Collector
> feature: #164 add solarwindsentityconnector to K8s distribution

- .github/actions/dockerScoutScan/action.yml
- .github/workflows/buildAndTest.yml
Updating tags to use the :latest ones that were published in the last release.
Testing passed
> chore: update tags for dockerscout 

- CHANGELOG.md
- cmd/solarwinds-otel-collector/components_k8s.go
- cmd/solarwinds-otel-collector/components_verified.go
**Tracking Issue:** https://github.com/solarwinds/solarwinds-otel-collector-releases/issues/165
> feature: #165 Add `routingconnector` to the k8s distribution

- CHANGELOG.md
- distributions/k8s/manifest.yaml
- distributions/playground/manifest.yaml
- distributions/verified/manifest.yaml
- pkg/version/version.go
Prepares release 0.127.5.
Green CI/CD pipeline
> chore: prepare release 0.127.5

- CHANGELOG.md
- pkg/version/version.go
Prepare release for version 0.127.7
CI/CD pipeline passing.
> chore: make release v0.127.7

- CHANGELOG.md
- pkg/version/version.go
chore: bugfix release v0.131.1
> chore: bugfix release v0.131.1

- CHANGELOG.md
- pkg/version/version.go
Prepares release 0.131.2
CI/CD
> chore: prepare release 0.131.2

- CHANGELOG.md
- pkg/version/version.go
Prepares release v0.131.3
CI/CD pipeline
> chore: prepare release v0.131.3

- CHANGELOG.md
- pkg/version/version.go
Prepares release v0.131.4
CI/CD pipeline.
> chore: prepare release 0.131.4

- CHANGELOG.md
- pkg/version/version.go
Prepares release v0.131.7
CI/CD pipeline.
> chore: prepare release 0.131.7

- README.md
Updating README.md with notice of new MQTT receiver.
> chore: update README.md by adding notice of MQTT receiver

- examples/integrations/host/config.yaml
> docs: Update host example config

- CHANGELOG.md
- Makefile
- README.md
- pkg/version/version.go
> chore: release of v0.136.0

- CHANGELOG.md
- pkg/version/version.go
Prepares release 0.136.1.
Fixed typo in previous release changelog
CI/CD pipeline green
> chore: prepare-release 0.136.1
