solarwinds/solarwinds-otel-collector-releases

- extension/solarwindsextension/internal/config.go
- extension/solarwindsextension/internal/datacell_test.go
The OTLP port number for SolarWinds SaaS is `443`, not `4317`. Apparently, it was replaced by mistake during recent changes.
It was tested locally by building a Docker image from this branch and running it against SolarWinds SaaS (`na-01`).
> [fix] Use Correct OTLP Port Number in Exporters

- internal/e2e/containers.go
- internal/e2e/go.mod
- internal/e2e/go.sum
- internal/e2e/signals_processing_test.go
- internal/e2e/testdata/emitting_collector.yaml
- internal/e2e/testdata/receiving_collector.yaml
This PR enables TLS in E2E tests. 
It achieves that by generating self-signed certificates during the tests to be used by the **test OTLP/gRPC Receiver** together with a root certificate added as trusted to the **tested solarwinds-otel-collector** container. 
- The current version overwrites `/etc/ssl/certs/ca-certificates.crt` in the Distroless image instead of only appending the generated test root certificate for simplicity. The image is stripped to a bare minimum and it's trickier to add it properly without modifying the actual image (Dockerfile).
- The `insecure` flag is not removed in this PR.
E2E tests passing.
> [test] Use Self-Signed Certificates to Use Exporter with TLS in E2E Tests

- .github/dependabot.yaml
- .github/workflows/buildAndDeploy.yml
- .github/workflows/checkPullRequestSemantics.yml
- README.md
- build/docker/README.md
- docs/development-guidelines.md
Created general document with development guidelines and expanded on naming conventions.
There is on difference to what was originally discussed for _Pull Requests_. The original proposal was to have
`[type]: #{issue number} Description of Changes` format.
Looking at the commit history in main I propose to keep the commit format:
`{type}: #{issue number} Description of Changes` (note the missing brackets), because the main squash commit option when merging by default **takes the title as commit message** using the brackets.. and this already led to disalignment. So I think sticking to this naming will provide more reliable commit naming outputs in main (which should be the main concern).
Also added new 'Check Pull Request Semantics' workflow to check correct semantics of the PR: 
- it …
> docs: Add Naming Guidelines

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/ISSUE_TEMPLATE/technical_improvement.yaml
- .github/workflows/buildAndDeploy.yml
This PR addresses following GH-related setup:
- adds new _'Technical Improvement'_ issue type to cover non-functional enhancements
- updates the build pipeline to be ran on `main` and `release` branches post-merge
- updates standing components enumeration to also contain extension
- ℹ️ **NOTE:** the manual upgrades should be switched to automated generation in future improvement
No testing required.
> chore: Adjust GH Setup - Technical Improvement Issue Type, Run Builds on Main and Release

- CHANGELOG.md
- exporter/solarwindsexporter/config.go
- exporter/solarwindsexporter/solarwinds_exporter.go
- extension/solarwindsextension/README.md
- extension/solarwindsextension/common_config.go
- extension/solarwindsextension/endpoint_config.go
- extension/solarwindsextension/extension.go
- extension/solarwindsextension/internal/heartbeat.go
- internal/e2e/signals_processing_test.go
This PR introduces a new resource attribute `sw.otelcol.collector.name` with the collector name as its value appended to all telemetry signals exporter from the Solarwinds Exporter.
It is tested in the `internal/e2e/signals_processing_test.go`
> feature: Append Collector Name to All Exported Signals in Exporter

- exporter/solarwindsexporter/config.go
- exporter/solarwindsexporter/solarwinds_exporter.go
- extension/solarwindsextension/common_config.go
- extension/solarwindsextension/extension.go
- extension/solarwindsextension/internal/heartbeat.go
- internal/e2e/signals_processing_test.go
- internal/e2e/without_entity_test.go
Doing this to associate all outputs with entity
Tagging all signals with entity_creation attribute.
Doing this in order for all collector outputs to be properly associated with created entity in SolarWinds Observability.
When without_entity: true is set in extension configuration, attribute is not added to any signals (and also removed from uptime heartbeat metric)
Manual testing against SWO
> feature: tag all signals with entity_creation attribute

- .github/workflows/buildAndDeploy.yml
- build/docker/Dockerfile.Windows-2022
- build/docker/Dockerfile.Windows-Runtime
- build/docker/Dockerfile.k8s.Windows-2022
- build/docker/Dockerfile.k8s.Windows-Runtime
- cmd/solarwinds-otel-collector/main.go
- cmd/solarwinds-otel-collector/main_others.go
- cmd/solarwinds-otel-collector/main_windows.go
* Adding windows build to the pipeline and to the multiarch
* Add possibility to run collector as windows service
* Since windows build takes a long time to run (30-40 minutes), so run it only on main and release branches to have some continuous check that build on windows still works. 
* Windows architectures are being added to multi-arch manifest
* I enabled run also on manual runs, here is manual run I triggered for this job to show that windows build is fine: https://github.com/solarwinds/solarwinds-otel-collector/actions/runs/13054997673
* NOTE: I couldn't test if the publishing part works
* This is prerequisite for: https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/879
> chore: Add Windows Architecture

- cmd/solarwinds-otel-collector/components_k8s.go
prerequisity for https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/879
> fix: Adding missing batch processor in k8s image distribution

- CHANGELOG.md
- build/docker/Dockerfile
- build/docker/Dockerfile.Windows-2022
- build/docker/Dockerfile.k8s
- build/docker/Dockerfile.k8s.Windows-2022
- cmd/solarwinds-otel-collector/go.mod
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- pkg/version/version.go
- receiver/swohostmetricsreceiver/go.mod
Updates Go build toolchain to 1.23.5 and releases a new image 0.113.8.
> chore: Update Go to 1.23.5 and release new image

- CHANGELOG.md
- README.md
- build/prepare-release.sh
- cmd/solarwinds-otel-collector/go.mod
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- pkg/version/version.go
- receiver/swohostmetricsreceiver/go.mod
Bumps the version to 0.119.0. Few additions made along the way:
- build: utilized `perl` instead of `sed` to guarantee same behavior across platforms (`sed` behaved differently with undesired results for MacOS)
- docs: adjusted CHANGELOG.md messages to follow same pattern that can be continued
- docs: fixed incorrect build command in README.md. Running sole `go build` without tags results in build failure.
Initiated GHA runs with uncomitted changes to validate the version update checks still work after migrating to `perl`
> chore: prepare release 0.119.0

- .github/actions/dockerScoutScan/action.yml
- .github/workflows/buildAndTest.yml
- .github/workflows/deploy.yml
When calling workflow from another, the callee is missing secret. It seems the secret has to be explicitly passed - `inherit` should pass all secrets to the callee workflow.
**Tracking Issue:** https://github.com/solarwinds/solarwinds-otel-collector/issues/56
No test cases added -> github configuration.
> chore: #56 Inherit secrets in build and test workflow

- .github/actions/analyzeCves/action.yml
- .github/workflows/deploy.yml
- .github/workflows/uploadSarifFiles.yml
Currently github.run_number which increments with each run of that workflow. For example run_number for upload sarif was `v4` but for deploy images it was `v10`.
I didn't want to change this specific tag since it would trigger changes in `build_and_test` workflow when saving windows images.
The solution is to use other tag `<release_version>-nanoserver-*` where release version can be easily parsed from `version.go` and should be equal in "deploy" and "upload sarif" workflows.
I would leave at least some sort of version metadata for each sarif file, so it is easy to identify which run the sarif output belongs to.
💡 Additionally, I am omitting exit-code and filter for cves as now it does not have any added value since the file is always empty :) We can take care of failing on …
> chore: #56 Fix artifact paths to sarif files

- .github/workflows/deploy.yml
Return exit codes to deploy workflow. Two exit codes were ignored so we were able to override existing images in the DockerHub with the same tag.
**Tracking Issue:** https://github.com/solarwinds/solarwinds-otel-collector/issues/56
The change was for example introduced here: https://github.com/solarwinds/solarwinds-otel-collector/pull/68/files
No test cases.
> chore: #56 Revert changes in exit codes

- CHANGELOG.md
- cmd/solarwinds-otel-collector/go.mod
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- pkg/version/version.go
- receiver/swohostmetricsreceiver/go.mod
- receiver/swok8sobjectsreceiver/go.mod
- receiver/swok8sobjectsreceiver/receiver.go
Update `swok8sobjectsreceiver` to send changes in other than `status`, `spec` and `metadata` sections. 
Do not report changes in `resourceVersion`. Remove `managedFileds` from manifests.
Release 0.119.4
Manual check with swi-k8s-opentelemetry-collector on docker-desktop
> chore: #96 updating swok8sobjectsreceiver

- CHANGELOG.md
- cmd/solarwinds-otel-collector/go.mod
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- pkg/version/version.go
- receiver/swohostmetricsreceiver/go.mod
- receiver/swok8sobjectsreceiver/go.mod
- receiver/swok8sobjectsreceiver/receiver.go
Updating swok8sobjectsreceover to remove managedFields from PULLed objects as well.
Increasing image version to 0.119.5
Manual test
> chore: #96 swok8sobjectsreceiver remove managed fields

- .github/workflows/buildAndTest.yml
- CHANGELOG.md
- cmd/solarwinds-otel-collector/go.mod
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- internal/k8sconfig/go.mod
- internal/tools/go.mod
- pkg/testutil/go.mod
- pkg/version/go.mod
- pkg/version/version.go
- processor/k8seventgenerationprocessor/go.mod
- receiver/swohostmetricsreceiver/go.mod
- receiver/swok8sobjectsreceiver/go.mod
Increases toolchain used across all components to utilize Go 1.23.6 to mitigate CVE-2025-22866. 
Difference can be seen in this [docker scout report](https://github.com/solarwinds/solarwinds-otel-collector/actions/runs/13857076111) with explicitly enabled windows builds to validate the vulnerability is no longer present.
Prepares release 0.119.7 to bring the fix.
E2E pipeline.
> chore: Fix CVE-2025-22866, prepare release 0.119.7

- CHANGELOG.md
- cmd/solarwinds-otel-collector/go.mod
- cmd/solarwinds-otel-collector/go.sum
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- pkg/version/version.go
- receiver/swohostmetricsreceiver/go.mod
- receiver/swok8sobjectsreceiver/go.mod
- receiver/swok8sobjectsreceiver/go.sum
Bumps the vulnerable version of github.com/expr-lang/expr dependency to v1.17.0, fixing [CVE-2025-29786](https://nvd.nist.gov/vuln/detail/CVE-2025-29786). Prepares release v0.119.9 to carry the fix.
Pipeline tests.
> chore: Address CVE-2025-29786, prepare release v0.119.9

- .github/workflows/deploy.yml
- CHANGELOG.md
- cmd/solarwinds-otel-collector/go.mod
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- pkg/version/version.go
- receiver/swohostmetricsreceiver/go.mod
- receiver/swok8sobjectsreceiver/go.mod
Prepares release v0.119.12.
Also provides tiny fix on propagation of 'latest' GH release. Previously, `latest=false` was explicitly set, thus no GH release had a chance to become latest. Omitting it completely will defer to default GH behavior utilizing timestamp, which should be suffictient.
Build pipeline should be sufficient.
> chore: prepare release 0.119.12

- .github/dependabot.yaml
When updating versions, dependabot puts in wrong versions for solarwinds-otel-collector-releases that we have to manually update.  But the versions are updated anyway when releasing, so we do not even have to use dependabot for them, therefore, I am excluding them.
Every section with patern "*" was given extra exclude pattern "*solarwinds-otel-collector-releases*"
Release process will be responsible for raising these versions.
> chore: excluded solarwinds-otel-collector-releases from dependabot

- .github/actions/dockerScoutScan/action.yml
- .github/workflows/buildAndTest.yml
Revert of https://github.com/solarwinds/solarwinds-otel-collector-releases/pull/123/files. Could not be done via GH revert action as some changes to some stuff changed already were made.
E2E pipeline.
> ci: revert to use more complex version fetch

- CHANGELOG.md
- cmd/solarwinds-otel-collector/go.mod
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- pkg/version/version.go
- receiver/swohostmetricsreceiver/go.mod
- receiver/swok8sobjectsreceiver/go.mod
Prepares release of v0.123.0
Includes fix for running `solarwinds` exporter. Exporter is now reported in collector internal telemetry as `otlp/solarwinds` exporter. 
By CI/CD pipeline.
> chore: preparing for release v0.123.0.

- CHANGELOG.md
- cmd/solarwinds-otel-collector/go.mod
- exporter/solarwindsexporter/go.mod
- extension/solarwindsextension/go.mod
- internal/e2e/go.mod
- pkg/version/version.go
- processor/swok8sworkloadtypeprocessor/go.mod
- receiver/swohostmetricsreceiver/go.mod
- receiver/swok8sobjectsreceiver/go.mod
chore: release 0.123.6
Another fail on publish, due to issue with paging in dockerhub api. Another round of hoping this time will be the last time.
This should have fixed it, to a degree.
https://github.com/solarwinds/solarwinds-otel-collector-releases/pull/157
> chore: release 0.123.6

- CHANGELOG.md
- Makefile
- build/prepare-release.sh
- distributions/k8s/manifest.yaml
- distributions/playground/manifest.yaml
- distributions/verified/manifest.yaml
- docs/development-guidelines.md
- pkg/version/version.go
Prepares release v0.127.1. Also updates prepare-release script to handle swotelcol and otelcol contrib dependencies separately; simplified to use single otel version.
To review changes separately:
- update of the script: https://github.com/solarwinds/solarwinds-otel-collector-releases/commit/f097fea6fb71b2600927d046c6b83b959ba4baa8
- release: https://github.com/solarwinds/solarwinds-otel-collector-releases/commit/06ed528bbc6ebcaa42082b6d7439130fb1a9b1bc
Green pipeline
> chore: prepare release 0.127.1

- .github/workflows/deploy.yml
Adds latest tag publishing to verify docker build pipeline. Since the step does both build+push of the image, no further action should be required.
Also fixed manifest creation for verified image, as it started off the playground instead of verified.
Will be validated with the next release. Pipeline should be unaffected otherwise.
> build: fix latest tag publishing

- CHANGELOG.md
- distributions/k8s/manifest.yaml
Add [pprofextension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/pprofextension) to the `k8s` distribution
**Tracking Issue:** https://github.com/solarwinds/solarwinds-otel-collector-releases/issues/196
n/a
> feature: #196 Add `pprofextension` to the `k8s` distribution

- CHANGELOG.md
- distributions/k8s/manifest.yaml
Add [logdedupprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/logdedupprocessor) to the `k8s` distribution
**Tracking Issue:** https://github.com/solarwinds/solarwinds-otel-collector-releases/issues/200
n/a
> feature: #200 Add `logdedupprocessor` to the `k8s` distribution

- internal/e2e/testdata/emitting_collector.yaml
- internal/e2e/testdata/emitting_collector_without_entity.yaml
- internal/e2e/testdata/swohostmetricsreceiver.yaml
- internal/e2e/testdata/swohostmetricsreceiver_default.yaml
Tests updated to use new otlp exporter and solarwinds processor.
Devtested against latest published docker image
> chore: updated e2e tests

- README.md
Added a mention of `swok8sworkloadstatusprocessor` processor in the table for verified distribution 
**Tracking Issue:** https://github.com/solarwinds/solarwinds-otel-collector-releases/issues/XXXX
n/a
> chore: Added a mention of `swok8sworkloadstatusprocessor` processor in the table for verified distribution 
